# Generated by Django 4.2.23 on 2026-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alloweduser_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedUser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=20),
        ),
    ]
